/*++

Module Name:

    device.c - Device handling events for example driver.

Abstract:

   This file contains the device entry points and callbacks.
    
Environment:

    Kernel-mode Driver Framework

--*/

#include "driver.h"
#include "device.tmh"

#ifdef ALLOC_PRAGMA
#pragma alloc_text (PAGE, RamDiskDriverCreateDevice)
#endif


NTSTATUS
RamDiskDriverCreateDevice(
    _Inout_ PWDFDEVICE_INIT DeviceInit
    )
/*++

Routine Description:

    Worker routine called to create a device and its software resources.

Arguments:

    DeviceInit - Pointer to an opaque init structure. Memory for this
                    structure will be freed by the framework when the WdfDeviceCreate
                    succeeds. So don't access the structure after that point.

Return Value:

    NTSTATUS

--*/
{
    WDF_OBJECT_ATTRIBUTES   deviceAttributes;
    PDEVICE_EXTENSION devext;
    WDFDEVICE device;
    NTSTATUS status;

    PAGED_CODE();

    WdfDeviceInitSetDeviceType(DeviceInit, FILE_DEVICE_DISK);
    WdfDeviceInitSetIoType(DeviceInit, WdfDeviceIoDirect);
    WdfDeviceInitSetExclusive(DeviceInit, FALSE);
    WDF_OBJECT_ATTRIBUTES_INIT_CONTEXT_TYPE(&deviceAttributes, DEVICE_EXTENSION);
    deviceAttributes.EvtCleanupCallback = RamDiskDriverEvtDriverContextCleanup;

    status = WdfDeviceCreate(&DeviceInit, &deviceAttributes, &device);

    if (NT_SUCCESS(status)) {
        //
        // Get a pointer to the device context structure that we just associated
        // with the device object. We define this structure in the device.h
        // header file. DeviceGetContext is an inline function generated by
        // using the WDF_DECLARE_CONTEXT_TYPE_WITH_NAME macro in device.h.
        // This function will do the type checking and return the device context.
        // If you pass a wrong object handle it will return NULL and assert if
        // run under framework verifier mode.
        //
        devext = DeviceGetExtension(device);
        //
        // Initialize the context.
        //
        status = InitDeviceExtension(devext);
        if (NT_SUCCESS(status))
        {
            /*status = AssignRamdiskDeviceName(device, DeviceInit);*/
            //assign device name. 
            //If name is not unique, we can't install ramdisk more than 1 instance.
            DECLARE_CONST_UNICODE_STRING(nt_name, NT_DEVICE_NAME);
            DECLARE_CONST_UNICODE_STRING(dos_name, DOS_DEVICE_NAME);

            status = WdfDeviceInitAssignName(DeviceInit, &nt_name);
            if (NT_SUCCESS(status))
            {
                status = WdfDeviceCreateSymbolicLink(device, &dos_name);
                if (!NT_SUCCESS(status))
                    TraceEvents(TRACE_LEVEL_ERROR, TRACE_DRIVER, "WdfDeviceCreateSymbolicLink() failed [%!STATUS!]", status);
            }
            else
                TraceEvents(TRACE_LEVEL_ERROR, TRACE_DRIVER, "WdfDeviceInitAssignName() failed [%!STATUS!]", status);
        }

        //
        // Create a device interface so that applications can find and talk
        // to us.
        //

        if (NT_SUCCESS(status))
        {
            status = WdfDeviceCreateDeviceInterface(
                device,
                &GUID_DEVINTERFACE_SMOKY_RAMDISK,
                NULL // ReferenceString
                );
        }
        //else
        //    TraceEvents(TRACE_LEVEL_ERROR, TRACE_DRIVER, "AssignRamdiskDeviceName() failed %!STATUS!", status);

        if (NT_SUCCESS(status)) {
            //
            // Initialize the I/O Package and any Queues
            //
            status = RamDiskDriverQueueInitialize(device);
        }
        //else
        //    TraceEvents(TRACE_LEVEL_ERROR, TRACE_DRIVER, "WdfDeviceCreateDeviceInterface() failed %!STATUS!", status);
    }

    return status;
}


